### ISSUE TITLE
Add lock file

### ISSUE THREAD

**Issue by colinking** [satya164/jest-file-snapshot#1]
Thanks for putting this repo together! Ran into a similar issue with a project I'm working on. Would love to see something similar in scope merged into `jest` 😄 

Any interest in adding a `package-lock.json` or adding a `yarn.lock` file?

**Comment by satya164** [comment]
There is a [`yarn.lock`](https://github.com/satya164/jest-file-snapshot/blob/master/yarn.lock)

Though it's not really useful for libraries since Yarn will ignore it.

**Comment by colinking** [comment]
Don't know how I missed that 🤦‍♂️ 

Great!
