### ISSUE TITLE
Snapshot file is not removed

### ISSUE THREAD

**Issue by wan54** [satya164/jest-file-snapshot#10]
```
describe('desc A', () => {
  it('should produce A', () => {
    expect('A').toMatchFile();
  });
});

describe('desc B', () => {
  it('should produce B', () => {
    expect('B').toMatchFile();
  });
});
```

Will produce two snapshot files in the `__file_snapshots__`

When one of the tests is removed the snapshot file of the removed test still exists in the folder. Expected to be removed.

**Comment by satya164** [comment]
To be able to delete snapshots we'd need to know all of the assertions present in the code and compare to the snapshots to find out which assertions are no longer present - and we don't have access to this information in a matcher.
