### ISSUE TITLE
assert seems backwards

### ISSUE THREAD

**Issue by jquense** [satya164/jest-file-snapshot#15]
The output seems reversed...the "expected" value in the diff is actually the "received", e.g. the incoming change. Just me or a real thing?

**Comment by satya164** [comment]
I'm not sure about the question. Are you talking about how jest prints the failure? The library just uses jest's API to write snapshot to separate file.

**Comment by jquense** [comment]
yes how jest prints it. This is not general to Jest tho my other asserts and normal snapshots show the correct thing. only the `toMatchFile` output is wrong

**Comment by jquense** [comment]
🎉 many thanks

**Comment by satya164** [comment]
Published the fix. Thanks for reporting :)
