### ISSUE TITLE
Snapshot behavior for objects different than built in jest snapshot

### ISSUE THREAD

**Issue by andreialecu** [satya164/jest-file-snapshot#19]
For anyone coming across this this library, be aware that it only seems to support JSON data. Objects/classes will serialize to `[Object object]` and that's what your snapshots will contain.

I've been able to combine this with [json-cycle](https://github.com/valery-barysok/json-cycle) to create useful snapshots, that were also much much faster than jest's default snapshotting implementation. 

For bigger objects, it would take upwards of 5 seconds to generate and analyze a snapshot using jest `.toMatchSnapshot()` while with this library and json-cycle, the time has been cut to a few miliseconds.

Implementation example:

```typescript
import { toMatchFile } from 'jest-file-snapshot';
import * as js from 'json-cycle';
import * as path from 'path';

expect.extend({ toMatchFile });

describe('some app feature', () => {
  describe('snapshot tests', () => {
    it('matches previous snaps of xyz', async () => {
      ...
      const data = ...;
      expect(JSON.stringify(js.decycle(data), null, 2)).toMatchFile(
        path.join(__dirname, '__file_snapshots__', 'snap-xyz.json')
      );
```

It would be nice if this was entirely built in. Issue #9 is also related.

**Comment by satya164** [comment]
https://github.com/satya164/jest-file-snapshot/issues/9#issuecomment-2221313686
