### ISSUE TITLE
Typescript Declarations

### ISSUE THREAD

**Issue by colinking** [satya164/jest-file-snapshot#2]
Since this repo monkey-patches `extends`, it'd be great to go ahead and export typing information to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Could be similar to this:

```
/// <reference types="jest" />

declare namespace jest {
  interface Matchers<R> {
    toMatchFile: (filename: string) => void
  }
   interface Expect {
    toMatchFile: (filename: string) => void
  }
}
```

see, f.e., https://github.com/jest-community/jest-extended/blob/master/types/index.d.ts

**Comment by satya164** [comment]
I think we could keep in the package since it's pretty small (if it's possible). Will be great if you could send a PR!

If it's not possible to keep it in the package or it's too much work for the user, then DefinitelyTyped sounds fine. I don't have experience with TypeScript, so not really the best person to decide :D

**Comment by satya164** [comment]
Released in https://github.com/satya164/jest-file-snapshot/releases/tag/v0.2.0

**Comment by fwouts** [comment]
I'm seeing an error when trying to do the following:

```typescript
import { toMatchFile } from "jest-file-snapshot";

expect.extend({ toMatchFile });
```

Error:
```
Module '"../node_modules/jest-file-snapshot"' has no exported member 'toMatchFile'.ts(2305)
```

It looks like `toMatchFile` might be missing from the TypeScript definitions?

**Comment by fwouts** [comment]
I did get it to work well with the following definition:
```typescript
import { DiffOptions } from 'jest-diff';

declare module "jest-file-snapshot" {
  export const toMatchFile: jest.CustomMatcher;
}

declare type FileMatcherOptions = {
  diff: DiffOptions
}

declare global {
  namespace jest {
    interface Matchers<R> {
      toMatchFile: (output: string, filename?: string, options?: FileMatcherOptions) => void
    }

    interface Expect {
      toMatchFile: (output: string, filename?: string, options?: FileMatcherOptions) => void
    }
  }
}

```

**Comment by satya164** [comment]
@fwouts yeah looks like we're missing it. do you want to send a pull request? :)
