### ISSUE TITLE
Cannot override 100 character limit from filenameify

### ISSUE THREAD

**Issue by TomStrepsil** [satya164/jest-file-snapshot#30]
[filenameify](https://github.com/sindresorhus/filenamify) has [a default 100 character limit](https://github.com/sindresorhus/filenamify/blob/7b52f70bb5fdc7f590327accadb542309d9e6401/filenamify.js#L4).  This means file snapshots cannot be saved with names over this length.

It'd be good to be able to pass through an option to override that.

**Comment by satya164** [comment]
Can we just pass `maxLength: Infinite` internally?
