### ISSUE TITLE
Component snapshot support

### ISSUE THREAD

**Issue by wan54** [satya164/jest-file-snapshot#9]
We've been looking for a tool like this. However, it does not work with our existing tools.

In our project we use enzyme's shallow, mount.

Currently we have the following:
```
const wrapper = shallow(<Component {...props} />);
expect(wrapper.get(0)).toMatchSnapshot();
```

Migrating to this tool by simply replacing the matcher does not work as expected
```
const wrapper = shallow(<Component {...props} />);
expect(wrapper.get(0)).toMatchFile();
```

Output in the snapshot file: `[object Object]`

Tested with react-test-renderer too and also produces `[object Object]`.

Tried with `.html()` of enzyme
```
const wrapper = shallow(<Component {...props} />);
expect(wrapper.html()).toMatchFile();
```

html is produced, but in one-liner, without formatting :(
```
<div class="some class"><span></span><div><div><h1>Details</h1></div></div></span></div>
```

It'd be great if this tool has the proper support for component snapshotting :)

**Comment by satya164** [comment]
The package is designed to snapshot strings or buffer (since that's what you write to files), while jest's built-in snapshots handles objects.

If you want to handle objects, you could do something like:

```js
expect.extend({
  toMatchFile: (content, filepath, options) =>
    toMatchFile(JSON.stringify(content), filepath, options),
});
```

Or replace `JSON.stringify` with a different method that prettifies the JSON output.
